# Install all R packages neccessary for Datenanalyse I+II 4 Apr 2024
# For Ubuntu do before:
#  sudo apt-get install r-cran-rjava
#  sudo apt install  default-jre default-jdk cmake libgsl-dev libudunits2-dev libgdal-dev
#  sudo R CMD javareconf
#
 if(!require("additivityTests")) install.packages("additivityTests")
 if(!require("agricolae")) install.packages("agricolae")
 if(!require("alphahull")) install.packages("alphahull")
 if(!require("Amelia")) install.packages("Amelia")
 if(!require("andrews")) install.packages("andrews")
 if(!require("ape")) install.packages("ape")
 if(!require("aplpack")) install.packages("aplpack")
 if(!require("ash")) install.packages("ash")
 if(!require("boot")) install.packages("boot")
 if(!require("car")) install.packages("car")
 if(!require("CHAID")) install.packages("CHAID", repos="http://R-Forge.R-project.org")
 if(!require("cluster")) install.packages("cluster")
 if(!require("coin")) install.packages("coin")
 if(!require("datasauRus")) install.packages("datasauRus")
 if(!require("dbscan")) install.packages("dbscan")
 if(!require("deldir")) install.packages("deldir")
 if(!require("DescTools")) install.packages("DescTools")
 if(!require("devtools")) install.packages("devtools")
 if(!require("e1071")) install.packages("e1071")
 if(!require("effectsize")) install.packages("effectsize")
 if(!require("effsize")) install.packages("effsize")
 if(!require("entropy")) install.packages("entropy")
 if(!require("extraDistr")) install.packages("extraDistr")
 if(!require("flexclust")) install.packages("flexclust")
 if(!require("foreign")) install.packages("foreign")
 if(!require("fpc")) install.packages("fpc")
 if(!require("gam")) install.packages("gam")
 if(!require("GGally")) install.packages("GGally")
 if(!require("ggmap")) install.packages("ggmap")
 if(!require("ggplot2")) install.packages("ggplot2")
 if(!require("glmnet")) install.packages("glmnet")
 if(!require("goftest")) install.packages("goftest")
 if(!require("gplots")) install.packages("gplots")
 # if(!require("grid")) install.packages("grid")
 if(!require("gridExtra")) install.packages("gridExtra")
 if(!require("hexbin")) install.packages("hexbin")
 if(!require("Hmisc")) install.packages("Hmisc")
 if(!require("HMMpa")) install.packages("HMMpa")
 if(!require("igraph")) install.packages("igraph")
 if(!require("lattice")) install.packages("lattice")
 if(!require("lawstat")) install.packages("lawstat")
 if(!require("lmtest")) install.packages("lmtest")
 if(!require("locfit")) install.packages("locfit")
 if(!require("MASS")) install.packages("MASS")
 if(!require("mclust")) install.packages("mclust")
 if(!require("mctest")) install.packages("mctest")
 if(!require("mgcv")) install.packages("mgcv")
 if(!require("mice")) install.packages("mice")
 if(!require("mitools")) install.packages("mitools")
 if(!require("mlbench")) install.packages("mlbench")
 if(!require("mlmi")) install.packages("mlmi")
 if(!require("mmstat4")) install.packages("mmstat4")
 if(!require("moments")) install.packages("moments")
 if(!require("NbClust")) install.packages("NbClust")
 if(!require("neuralnet")) install.packages("neuralnet")
 if(!require("nnet")) install.packages("nnet")
 if(!require("nortest")) install.packages("nortest")
 if(!require("np")) install.packages("np")
 if(!require("olsrr")) install.packages("olsrr")
 if(!require("outliers")) install.packages("outliers")
 if(!require("parameters")) install.packages("parameters")
 if(!require("paran")) install.packages("paran")
 # if(!require("plot.3d")) install.packages("plot.3d")
 if(!require("plot.matrix")) install.packages("plot.matrix")
 if(!require("plotrix")) install.packages("plotrix")
 if(!require("printr")) install.packages("printr")
 if(!require("proxy")) install.packages("proxy")
 if(!require("pscl")) install.packages("pscl")
 if(!require("psych")) install.packages("psych")
 # if(!require("qualityTools")) install.packages("qualityTools")
 if(!require("QuantPsyc")) install.packages("QuantPsyc")
 if(!require("randomForest")) install.packages("randomForest")
 if(!require("RColorBrewer")) install.packages("RColorBrewer")
 if(!require("reshape2")) install.packages("reshape2")
 if(!require("reticulate")) install.packages("reticulate")
 # if(!require("rggobi")) install.packages("rggobi")
 if(!require("rio")) install.packages("rio")
 if(!require("robustbase")) install.packages("robustbase")
 if(!require("rpart")) install.packages("rpart")
 if(!require("rpart.plot")) install.packages("rpart.plot")
 if(!require("sampling")) install.packages("sampling")
 if(!require("scagnostics")) install.packages("scagnostics")
 if(!require("scatterplot3d")) install.packages("scatterplot3d")
 if(!require("shiny")) install.packages("shiny")
 # if(!require("shinyApp")) install.packages("shinyApp")
 if(!require("shinydashboard")) install.packages("shinydashboard")
 # if(!require("shinyExample")) install.packages("shinyExample")
 if(!require("shinyWidgets")) install.packages("shinyWidgets")
 if(!require("sm")) install.packages("sm")
 if(!require("smvgraph")) install.packages("smvgraph")
 if(!require("spData")) install.packages("spData")
 if(!require("spdep")) install.packages("spdep")
 # if(!require("tabplot")) install.packages("tabplot")
 if(!require("TeachingDemos")) install.packages("TeachingDemos")
 if(!require("tibble")) install.packages("tibble")
 if(!require("Transform")) install.packages("Transform")
 if(!require("UsingR")) install.packages("UsingR")
 if(!require("vcd")) install.packages("vcd")
 if(!require("vcdExtra")) install.packages("vcdExtra")
 if(!require("VIM")) install.packages("VIM")
 if(!require("vioplot")) install.packages("vioplot")
 if(!require("viridisLite")) install.packages("viridisLite")
 if(!require("xlsx")) install.packages("xlsx")
 if(!require("xtable")) install.packages("xtable")
