# Install all R packages neccessary for Datenanalyse I+II 4 Apr 2024
# For Ubuntu do before:
#  sudo apt-get install libgmp-dev
#  sudo apt-get install libmpfr-dev
#  sudo apt-get install r-cran-rjava
#  sudo apt install  default-jre default-jdk cmake libgsl-dev libudunits2-dev libgdal-dev
#  sudo R CMD javareconf
#
 library("mmstat4")
 if(pkgMissing("additivityTests")) install.packages("additivityTests")
 if(pkgMissing("agricolae")) install.packages("agricolae")
 if(pkgMissing("alphahull")) install.packages("alphahull")
 if(pkgMissing("Amelia")) install.packages("Amelia")
 if(pkgMissing("andrews")) install.packages("andrews")
 if(pkgMissing("ape")) install.packages("ape")
 if(pkgMissing("aplpack")) install.packages("aplpack")
 if(pkgMissing("ash")) install.packages("ash")
 if(pkgMissing("boot")) install.packages("boot")
 if(pkgMissing("car")) install.packages("car")
 if(pkgMissing("CHAID")) install.packages("CHAID", repos="http://R-Forge.R-project.org")
 if(pkgMissing("cluster")) install.packages("cluster")
 if(pkgMissing("coin")) install.packages("coin")
 if(pkgMissing("datasauRus")) install.packages("datasauRus")
 if(pkgMissing("dbscan")) install.packages("dbscan")
 if(pkgMissing("deldir")) install.packages("deldir")
 if(pkgMissing("DescTools")) install.packages("DescTools")
 if(pkgMissing("devtools")) install.packages("devtools")
 if(pkgMissing("e1071")) install.packages("e1071")
 if(pkgMissing("effectsize")) install.packages("effectsize")
 if(pkgMissing("effsize")) install.packages("effsize")
 if(pkgMissing("entropy")) install.packages("entropy")
 if(pkgMissing("extraDistr")) install.packages("extraDistr")
 if(pkgMissing("flexclust")) install.packages("flexclust")
 if(pkgMissing("foreign")) install.packages("foreign")
 if(pkgMissing("fpc")) install.packages("fpc")
 if(pkgMissing("gam")) install.packages("gam")
 if(pkgMissing("GGally")) install.packages("GGally")
 if(pkgMissing("ggmap")) install.packages("ggmap")
 if(pkgMissing("ggplot2")) install.packages("ggplot2")
 if(pkgMissing("glmnet")) install.packages("glmnet")
 if(pkgMissing("goftest")) install.packages("goftest")
 if(pkgMissing("gplots")) install.packages("gplots")
 # if(pkgMissing("grid")) install.packages("grid")
 if(pkgMissing("gridExtra")) install.packages("gridExtra")
 if(pkgMissing("hexbin")) install.packages("hexbin")
 if(pkgMissing("HH")) install.packages("HH")
 if(pkgMissing("Hmisc")) install.packages("Hmisc")
 if(pkgMissing("HMMpa")) install.packages("HMMpa")
 if(pkgMissing("igraph")) install.packages("igraph")
 if(pkgMissing("lattice")) install.packages("lattice")
 if(pkgMissing("lawstat")) install.packages("lawstat")
 if(pkgMissing("lmtest")) install.packages("lmtest")
 if(pkgMissing("locfit")) install.packages("locfit")
 if(pkgMissing("MASS")) install.packages("MASS")
 if(pkgMissing("mclust")) install.packages("mclust")
 if(pkgMissing("mctest")) install.packages("mctest")
 if(pkgMissing("mgcv")) install.packages("mgcv")
 if(pkgMissing("mice")) install.packages("mice")
 if(pkgMissing("mitools")) install.packages("mitools")
 if(pkgMissing("mlbench")) install.packages("mlbench")
 if(pkgMissing("mlmi")) install.packages("mlmi")
 if(pkgMissing("mmstat4")) install.packages("mmstat4")
 if(pkgMissing("moments")) install.packages("moments")
 if(pkgMissing("NbClust")) install.packages("NbClust")
 if(pkgMissing("neuralnet")) install.packages("neuralnet")
 if(pkgMissing("nnet")) install.packages("nnet")
 if(pkgMissing("nortest")) install.packages("nortest")
 if(pkgMissing("np")) install.packages("np")
 if(pkgMissing("olsrr")) install.packages("olsrr")
 if(pkgMissing("outliers")) install.packages("outliers")
 if(pkgMissing("parameters")) install.packages("parameters")
 if(pkgMissing("paran")) install.packages("paran")
 # if(pkgMissing("plot.3d")) install.packages("plot.3d")
 if(pkgMissing("plot.matrix")) install.packages("plot.matrix")
 if(pkgMissing("plotrix")) install.packages("plotrix")
 if(pkgMissing("printr")) install.packages("printr")
 if(pkgMissing("proxy")) install.packages("proxy")
 if(pkgMissing("pscl")) install.packages("pscl")
 if(pkgMissing("psych")) install.packages("psych")
 # if(pkgMissing("qualityTools")) install.packages("qualityTools")
 if(pkgMissing("QuantPsyc")) install.packages("QuantPsyc")
 if(pkgMissing("randomForest")) install.packages("randomForest")
 if(pkgMissing("RColorBrewer")) install.packages("RColorBrewer")
 if(pkgMissing("reshape2")) install.packages("reshape2")
 if(pkgMissing("reticulate")) install.packages("reticulate")
 # if(pkgMissing("rggobi")) install.packages("rggobi")
 if(pkgMissing("rio")) install.packages("rio")
 if(pkgMissing("robustbase")) install.packages("robustbase")
 if(pkgMissing("rpart")) install.packages("rpart")
 if(pkgMissing("rpart.plot")) install.packages("rpart.plot")
 if(pkgMissing("sampling")) install.packages("sampling")
 if(pkgMissing("scagnostics")) install.packages("scagnostics")
 if(pkgMissing("scatterplot3d")) install.packages("scatterplot3d")
 if(pkgMissing("shiny")) install.packages("shiny")
 # if(pkgMissing("shinyApp")) install.packages("shinyApp")
 if(pkgMissing("shinydashboard")) install.packages("shinydashboard")
 # if(pkgMissing("shinyExample")) install.packages("shinyExample")
 if(pkgMissing("shinyWidgets")) install.packages("shinyWidgets")
 if(pkgMissing("sm")) install.packages("sm")
 if(pkgMissing("smvgraph")) install.packages("smvgraph")
 if(pkgMissing("spData")) install.packages("spData")
 if(pkgMissing("spdep")) install.packages("spdep")
 # if(pkgMissing("tabplot")) install.packages("tabplot")
 if(pkgMissing("TeachingDemos")) install.packages("TeachingDemos")
 if(pkgMissing("tibble")) install.packages("tibble")
 if(pkgMissing("Transform")) install.packages("Transform")
 if(pkgMissing("UsingR")) install.packages("UsingR")
 if(pkgMissing("vcd")) install.packages("vcd")
 if(pkgMissing("vcdExtra")) install.packages("vcdExtra")
 if(pkgMissing("VIM")) install.packages("VIM")
 if(pkgMissing("vioplot")) install.packages("vioplot")
 if(pkgMissing("viridisLite")) install.packages("viridisLite")
 if(pkgMissing("xlsx")) install.packages("xlsx")
 if(pkgMissing("xtable")) install.packages("xtable")
