data("Boston", package="MASS")
library("car")
lm     <- lm(medv~lstat, data=Boston)
lmboot <- Boot(lm)
pdf("lstat.pdf", width=10, height=3)
hist(lmboot)
dev.off()
if (interactive()) browseURL(paste0(getwd(),"/lstat.pdf"))
